CC=gcc
CFLAGS= -g

all : clean common.o server.o client.o main


#Third Party Libraries
crc32.o:
	$(CC) $(CFLAGS) -c library/crc32/crc32.c


#Common
sendrecv.o:
	$(CC) $(CFLAGS) -c common/sendrecv.c

common.o: crc32.o sendrecv.o
	$(CC) $(CFLAGS) -c common/common.c


#Server
group_server.o: common.o
	$(CC) $(CFLAGS) -c server/group.c -o group_server.o

file_transfer_server.o: common.o
	$(CC) $(CFLAGS) -c server/file_transfer_server.c

server.o: group_server.o file_transfer_server.o
	$(CC) $(CFLAGS) -c server/server.c 


#Client
group_client.o: common.o
	$(CC) $(CFLAGS) -c client/group.c -o group_client.o

file_transfer_client.o: common.o
	$(CC) $(CFLAGS) -c client/file_transfer_client.c

client.o: group_client.o file_transfer_client.o
	$(CC) $(CFLAGS) -c client/client.c


#Main
main: server.o client.o
	$(CC) $(CFLAGS) -pthread -o a.out main.c *.o
	rm -f *.o

clean:
	rm -f *.o a.out
	rm -rf files_received
	rm -rf GROUP_FILES

