CC=gcc
CFLAGS= -g

all : clean common.o server.o client.o main

#Common/Libraries
crc32.o:
	$(CC) $(CFLAGS) -c library/crc32/crc32.c

common.o: crc32.o
	$(CC) $(CFLAGS) -c common/common.c


#Server
group.o: common.o
	$(CC) $(CFLAGS) -c server/group.c

file_transfer_server.o: common.o
	$(CC) $(CFLAGS) -c server/file_transfer_server.c

server.o: group.o file_transfer_server.o
	$(CC) $(CFLAGS) -c server/server.c 


#Client
file_transfer_client.o: common.o
	$(CC) $(CFLAGS) -c client/file_transfer_client.c

client.o: file_transfer_client.o
	$(CC) $(CFLAGS) -c client/client.c


#Main
main: server.o client.o
	$(CC) $(CFLAGS) -o a.out main.c *.o
	rm -f *.o

clean:
	rm -f *.o a.out

